package ufc.quixada.npi.afastamento.model;

public enum Notificacao {
	
	RESERVA_INCLUIDA,
	RESERVA_INCLUIDA_RANKING,
	RESERVA_EXCLUIDA,
	RESERVA_CANCELADA,
	RESERVA_ALTERADA,
	RESERVA_HOMOLOGADA,
	ADMISSAO_ALTERADA
}
