package ufc.quixada.npi.afastamento.model;

public enum Notificacao {
	
	RANKING_ATUALIZADO,
	RESERVA_INCLUIDA,
	RESERVA_ATUALIZADA,
	RESERVA_EXCLUIDA,
	PERIODO_ENCERRADO,
	GERENCIAMENTO_DE_RESERVAS,
	ALTERACAO_DADOS_CADASTRAIS,
	LISTA_DOCENTES_ATUALIZADAS,
	ATUALIZACAO_CONCEITO,
	ADMISSAO_ATUALIZADA;
}
